<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>41601048-3f8f-4922-8ccb-7ad214b71a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7621a4b-7b75-482c-b744-064ea74b78f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99d3087e-eb0b-4b3f-827d-4c523ae7d37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-r-full border border-transparent bg-primary-50 px-6 py-3 text-sm font-semibold leading-4 text-primary-400 hover:bg-primary-100 focus:ring-2 focus:ring-primary-400 focus:ring-offset-2</value>
      <webElementGuid>22343738-dce3-417c-a25b-0fd55f6970f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>98db3ad1-7866-4be8-b82d-fa92dea93019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;ease-out z-50 bg-white transition-all  duration-1000&quot;]/nav[@class=&quot;fixed top-0 z-50 w-full border-b bg-white&quot;]/div[@class=&quot;mx-auto max-w-7xl px-4 sm:items-center sm:px-6 lg:px-8&quot;]/div[@class=&quot;relative flex items-center justify-between py-1.5 lg:gap-4 lg:py-2&quot;]/div[@class=&quot;w-96 hidden lg:flex lg:items-center lg:justify-end xl:col-span-4&quot;]/div[@class=&quot;inline-flex&quot;]/button[@class=&quot;rounded-r-full border border-transparent bg-primary-50 px-6 py-3 text-sm font-semibold leading-4 text-primary-400 hover:bg-primary-100 focus:ring-2 focus:ring-primary-400 focus:ring-offset-2&quot;]</value>
      <webElementGuid>c69446b6-bb9d-4b8b-934c-f9cc42b30cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>1503d3c0-6f90-4508-9f25-6f53eec88587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/nav/div[2]/div/div[4]/div/button[2]</value>
      <webElementGuid>e87ed5d4-598d-4df3-9ff7-c9bd5e93289a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Sekarang'])[1]/following::button[1]</value>
      <webElementGuid>cabb74ee-04a9-46d2-bd65-8b9c2467e4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open sidebar'])[1]/following::button[2]</value>
      <webElementGuid>39d88fb7-0de0-48a2-85a6-0669f3eed30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>b07d29fa-bc67-419a-bee7-31125246c7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>12a6a9e5-8060-47ca-a946-b4cb1a6d2b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>89f32a43-ac54-42c3-98b4-359bcb6ba264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
