<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>b8a77e06-0cba-44fa-8e0c-55f697e6d056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>047ec66d-0294-4298-960c-01df02b87fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2826a76f-3883-4878-b3ea-9fe784a56cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-r-full border border-transparent bg-primary-50 px-6 py-3 text-sm font-semibold leading-4 text-primary-400 hover:bg-primary-100 focus:ring-2 focus:ring-primary-400 focus:ring-offset-2</value>
      <webElementGuid>ed65a967-9e09-47e7-b8f4-a3503626b066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>674366df-c244-41c9-bf0e-f2e2d1fd092e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;ease-out z-50 bg-white transition-all  duration-1000&quot;]/nav[@class=&quot;fixed top-0 z-50 w-full border-b bg-white&quot;]/div[@class=&quot;mx-auto max-w-7xl px-4 sm:items-center sm:px-6 lg:px-8&quot;]/div[@class=&quot;relative flex items-center justify-between py-1.5 lg:gap-4 lg:py-2&quot;]/div[@class=&quot;w-96 hidden lg:flex lg:items-center lg:justify-end xl:col-span-4&quot;]/div[@class=&quot;inline-flex&quot;]/button[@class=&quot;rounded-r-full border border-transparent bg-primary-50 px-6 py-3 text-sm font-semibold leading-4 text-primary-400 hover:bg-primary-100 focus:ring-2 focus:ring-primary-400 focus:ring-offset-2&quot;]</value>
      <webElementGuid>a74af12a-27a6-4b5e-8b0f-831d53797f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>4e21da7f-e0c2-424f-adc2-afdcd9b67a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/nav/div[2]/div/div[4]/div/button[2]</value>
      <webElementGuid>023282bb-78d7-4690-888b-1e70a4ea66f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Sekarang'])[1]/following::button[1]</value>
      <webElementGuid>4e686e63-06c3-41fd-a257-cde592a3d7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open sidebar'])[1]/following::button[2]</value>
      <webElementGuid>6d701742-c454-49d5-b7b9-1c4e00806e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>57faeb88-3c73-482d-8c39-d773ba7e20f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>41ebf522-5f30-4641-bf31-2ae93567f598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>ef347938-94ad-49eb-9521-440c746ce76a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
