<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_phoneNumber</name>
   <tag></tag>
   <elementGuidId>fc8ac4d9-5ef7-40d6-8046-da4113d211b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phoneNumber&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28ab4dbd-19d4-46c8-8fce-cffcce6c5797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input</value>
      <webElementGuid>705d4b3e-6299-4008-aaf8-b6d27ef11b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1 (702) 123-4567</value>
      <webElementGuid>9e237e95-511d-4f12-94ee-77258a7a7b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8e4845f4-76cc-43fa-ade1-f26be2999529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>b8e4d898-0aff-4be6-9dd1-286695427495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+62 8</value>
      <webElementGuid>1c368732-7636-4079-bb68-0b5852bb80f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;h-[100vh]&quot;]/div[@class=&quot;flex min-h-full&quot;]/div[@class=&quot;flex flex-1 flex-col justify-center px-4 py-12 sm:px-6 md:px-12 xl:flex-none xl:px-24&quot;]/div[@class=&quot;mx-auto w-full&quot;]/div[@class=&quot;mt-8&quot;]/div[@class=&quot;mt-6&quot;]/form[@class=&quot;space-y-6&quot;]/div[1]/div[@class=&quot;mt-1&quot;]/div[@class=&quot;react-tel-input&quot;]/input[@class=&quot;form-control form-input&quot;]</value>
      <webElementGuid>f5eed1d2-a266-4f75-89cf-206d5bcbbdd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phoneNumber']</value>
      <webElementGuid>88da6d33-5a4c-4c71-a0f8-b6e7f35447d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>94b31021-da7f-43a1-bb2e-125875ab06a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4ce26411-e064-4b67-a0e5-e024e679e8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '1 (702) 123-4567' and @type = 'tel' and @name = 'phoneNumber']</value>
      <webElementGuid>3faa7365-59d7-4988-9758-b44c9875bb5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
