<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verifikasi No. HP_my-10 block h-14 w-_06ef65</name>
   <tag></tag>
   <elementGuidId>1146dbb1-dd9d-4f5f-a789-9af1fe8e3038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00143c48-5a00-4cb9-9cbe-1d697e94b680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>689e65f8-84bc-45f3-bc6b-a1a890983ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>d8f68da3-87c1-4947-bc94-2ae843cb96ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>8198dc84-dfb8-4083-9a00-a87e675021cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d{1}</value>
      <webElementGuid>b056be34-74e1-4bf3-a8ac-cca20d9ee274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>4518227e-c311-4bbf-82b8-4df99239abe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-10 block h-14 w-full appearance-none rounded-full border border-gray-300 p-0 text-center font-bold shadow-sm placeholder:text-gray-400 focus:border-primary-400 focus:outline-none focus:ring-primary-400 sm:text-sm md:px-6 md:py-8 xl:text-base</value>
      <webElementGuid>69b2eb7c-9d81-424d-965d-894f86e42297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;my-16 bg-white&quot;]/div[@class=&quot;mx-auto max-w-3xl px-4 py-10 sm:px-6 md:py-20 lg:px-8&quot;]/form[@class=&quot;shadow-default mx-auto flex max-w-2xl flex-col rounded-2xl bg-white&quot;]/div[@class=&quot;relative flex-1 px-6 py-16 md:px-20&quot;]/div[@class=&quot;grid grid-cols-6 gap-1&quot;]/input[@class=&quot;my-10 block h-14 w-full appearance-none rounded-full border border-gray-300 p-0 text-center font-bold shadow-sm placeholder:text-gray-400 focus:border-primary-400 focus:outline-none focus:ring-primary-400 sm:text-sm md:px-6 md:py-8 xl:text-base&quot;]</value>
      <webElementGuid>7584e550-5ebc-4823-ade3-eb63237af888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>25deaf2e-5528-48a1-8d89-60e8444cfd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/div/form/div/div[3]/input</value>
      <webElementGuid>d513b1d2-832b-49a8-a811-0c067092914d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e005f233-51f7-40af-a0b7-9e9629c82ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>c0a5d465-4ae0-4872-a93d-c6c3d220f51b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
