<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reset Password_my-10 block h-14 w-ful_53d72f</name>
   <tag></tag>
   <elementGuidId>c3f081ef-8401-4902-9137-2c99cff0f32a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>042ae122-e976-4d23-a2c1-f6c9ae7e6224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21b79035-3ae5-4306-b15e-f08c64d88b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>d88a19ce-19dd-4573-8eda-1817903deb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>e1aaa3dd-e5e0-414c-82cd-0939dc353e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d{1}</value>
      <webElementGuid>b543143e-4d1d-441b-b624-a604d6ffee77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>bfeddb0d-382b-40d0-9b1c-a70f89143485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-10 block h-14 w-full appearance-none rounded-full border border-gray-300 p-0 text-center font-bold shadow-sm placeholder:text-gray-400 focus:border-primary-400 focus:outline-none focus:ring-primary-400 sm:text-sm md:px-6 md:py-8 xl:text-base</value>
      <webElementGuid>5c7ee89d-b2a5-44f7-90e2-fa25de7b8fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;my-16 bg-white&quot;]/div[@class=&quot;mx-auto max-w-3xl px-4 py-10 sm:px-6 md:py-20 lg:px-8&quot;]/div[@class=&quot;shadow-default mx-auto flex max-w-2xl flex-col rounded-2xl bg-white&quot;]/div[@class=&quot;relative flex-1 px-6 py-16 md:px-20&quot;]/div[@class=&quot;grid grid-cols-6 gap-1&quot;]/input[@class=&quot;my-10 block h-14 w-full appearance-none rounded-full border border-gray-300 p-0 text-center font-bold shadow-sm placeholder:text-gray-400 focus:border-primary-400 focus:outline-none focus:ring-primary-400 sm:text-sm md:px-6 md:py-8 xl:text-base&quot;]</value>
      <webElementGuid>167d681b-b93f-47f1-af3c-4f90eec5d5d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>63c5eae3-e419-4f30-82d0-8d4c0a41dbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/div/div/div/div[3]/input</value>
      <webElementGuid>c780101d-ef79-4624-8cf4-b833f40f3926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>8470ef0c-ac62-4ac0-af3c-9d5a133056dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>56e3546a-0208-4e32-8857-db6bf629bec7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
