<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_QRIS</name>
   <tag></tag>
   <elementGuidId>a9209727-831f-41b9-a93e-3ea4242f0d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.truncate.text-sm.font-bold.text-gray-900</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//dd[@id='headlessui-disclosure-panel-:rh:']/div/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>a11c4a12-2f5a-4887-8090-f744267b6551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate text-sm font-bold text-gray-900</value>
      <webElementGuid>635dfb98-b0cc-4490-a550-076bafc72463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QRIS</value>
      <webElementGuid>59d8accf-a8cc-4c0d-aa3f-677e9b15badd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-disclosure-panel-:rh:&quot;)/div[@class=&quot;bg-gray-100  relative mx-auto w-[90%] cursor-pointer rounded-lg px-4 py-3 hover:ring-2 hover:ring-primary-400&quot;]/div[@class=&quot;flex items-center justify-between gap-3&quot;]/div[@class=&quot;w-full flex-1 truncate&quot;]/h3[@class=&quot;truncate text-sm font-bold text-gray-900&quot;]</value>
      <webElementGuid>5dc1cf82-d6ba-4cce-9aff-b35682c3c37d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dd[@id='headlessui-disclosure-panel-:rh:']/div/div/div/h3</value>
      <webElementGuid>8b81a4ff-b7b2-4512-ae8e-15c969891bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 1.922,-'])[1]/following::h3[1]</value>
      <webElementGuid>df0aa56e-63b9-4859-81c0-a88417108916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QRIS'])[1]/following::h3[1]</value>
      <webElementGuid>7ea7abd9-6659-4afd-885c-97e605471dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E - Wallet'])[1]/preceding::h3[1]</value>
      <webElementGuid>49b85554-ac8c-4e66-9c42-6c208ce4fc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 1.948,-'])[1]/preceding::h3[1]</value>
      <webElementGuid>3f982388-4d5a-45a8-ac57-15bd147dcf42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/div/div/div/h3</value>
      <webElementGuid>14b7163a-7d0b-4876-a868-daf24d2507dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'QRIS' or . = 'QRIS')]</value>
      <webElementGuid>4ba106f2-02d2-4aea-b5b8-43db52313f81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
