<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Voucher_voucher</name>
   <tag></tag>
   <elementGuidId>0b5cda99-7af7-423f-816e-528fac79203c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;voucher&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='voucher']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5e04eb2-0598-4af3-aaf5-b96e9abcfe23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba8678fc-e5aa-4ee5-8538-3b91d5b65dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>voucher</value>
      <webElementGuid>4df472fa-50d2-4128-ba5c-0da0f69c7b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-20 block w-full rounded-[10px] border-gray-300 py-2 pl-10 text-xs focus:border-2 focus:border-[#01860f] focus:ring-0 sm:text-sm</value>
      <webElementGuid>0d5c8d84-0799-428d-89d0-52ad909de629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kode voucher</value>
      <webElementGuid>d77c9946-1494-471d-9f05-ef0cfe8f4c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-white&quot;]/div[@class=&quot;mx-auto max-w-7xl pb-10 sm:px-6 lg:px-8&quot;]/div[@class=&quot;grid grid-cols-1 items-start gap-4 lg:grid-cols-3 lg:gap-8&quot;]/div[@class=&quot;grid grid-cols-1 gap-4&quot;]/section[1]/div[@class=&quot;shadow-form rounded-[8px] bg-white px-6 py-5&quot;]/div[@class=&quot;hidden md:block&quot;]/div[@class=&quot;mt-4 space-y-4&quot;]/div[@class=&quot;relative w-full items-center rounded-full&quot;]/input[@class=&quot;z-20 block w-full rounded-[10px] border-gray-300 py-2 pl-10 text-xs focus:border-2 focus:border-[#01860f] focus:ring-0 sm:text-sm&quot;]</value>
      <webElementGuid>d7bbadfb-6fc3-4078-beab-56c4f1d1302a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='voucher']</value>
      <webElementGuid>b2626987-dbf6-490d-8f88-21131c6b9fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div/div[2]/section/div/div[2]/div/div/input</value>
      <webElementGuid>af542445-ac58-451e-bb6d-8e2ba117f421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div/input</value>
      <webElementGuid>e0f700fa-d026-4783-8187-b5bc69a798b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'voucher' and @placeholder = 'Masukkan kode voucher']</value>
      <webElementGuid>04a673bf-0581-403a-a8c0-1cc3759a1f13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
