<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verifikasi 2 Langkah_block h-14 w-ful_31e884</name>
   <tag></tag>
   <elementGuidId>03316c75-20d7-4986-b73d-0cbbb910c228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17e68ffe-9daa-4a89-93a8-e92402f4ec07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1556d28f-9d0a-430d-8e1b-0186c9d08651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>31a244fe-a3d4-40d8-a800-0134596dabf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Please enter OTP character 1</value>
      <webElementGuid>d1dbaf80-64c9-449b-afb8-819270604bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block h-14 !w-full rounded-full border border-gray-300 p-0 text-center font-bold shadow-sm placeholder:text-gray-400 focus:border-primary-400 focus:outline-none focus:ring-primary-400 sm:text-sm md:px-6 md:py-8 xl:text-base</value>
      <webElementGuid>e934249b-6508-4adf-8788-e046a3916b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d3514d5-ef8e-4b83-8206-dc418b13d3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>708e70a5-9966-43d7-84c4-745580da3296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;my-16 bg-white&quot;]/div[@class=&quot;mx-auto max-w-3xl px-4 py-10 sm:px-6 md:py-20 lg:px-8&quot;]/form[@class=&quot;shadow-default mx-auto flex max-w-2xl flex-col rounded-2xl bg-white&quot;]/div[@class=&quot;relative flex-1 px-6 py-16 md:px-20&quot;]/div[@class=&quot;grid grid-cols-6 my-10 gap-1 w-full&quot;]/input[@class=&quot;block h-14 !w-full rounded-full border border-gray-300 p-0 text-center font-bold shadow-sm placeholder:text-gray-400 focus:border-primary-400 focus:outline-none focus:ring-primary-400 sm:text-sm md:px-6 md:py-8 xl:text-base&quot;]</value>
      <webElementGuid>82d08cc4-a1f7-41b0-af23-05eca6c8cfcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>9b3effea-4cde-4c0c-a5f1-c9f462c86c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/div/form/div/div[3]/input</value>
      <webElementGuid>e43fa730-8426-4e8c-9a7e-e3eeb636943e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a53ed686-5adf-4640-b2d3-f45b0add377f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>afcb0788-c175-4753-9aab-febeade890b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
