<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_phoneNumber</name>
   <tag></tag>
   <elementGuidId>be26958d-d969-4533-96f9-f05baf01105a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phoneNumber&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9fe2969-562d-460a-97c7-4189b7c44155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input</value>
      <webElementGuid>2102ee6d-7aa8-4e2c-9e11-c4257d4e7211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1 (702) 123-4567</value>
      <webElementGuid>c0767c6c-432b-4c00-8657-96488dea910a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>94b45734-e060-4cf6-aea4-37b4e1f2f952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>e55f1a8f-7676-4677-a7f4-31f8448d4220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+62 8</value>
      <webElementGuid>a8fe5d78-9478-4d29-ad2e-cf586c206499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex min-h-full&quot;]/div[@class=&quot;flex flex-1 flex-col justify-center px-4 py-12 sm:px-6 md:px-12 xl:flex-none xl:px-24&quot;]/div[@class=&quot;mx-auto w-full&quot;]/div[@class=&quot;mt-8&quot;]/div[@class=&quot;mt-6&quot;]/form[@class=&quot;space-y-6&quot;]/div[3]/div[@class=&quot;mt-1&quot;]/div[@class=&quot;react-tel-input&quot;]/input[@class=&quot;form-control form-input&quot;]</value>
      <webElementGuid>5000af1f-b510-4c2e-96ba-a9dfb3e66351</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phoneNumber']</value>
      <webElementGuid>3304133e-04a5-4c8f-bd2c-8ea919e01d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[2]/div[2]/div/form/div[3]/div/div/input</value>
      <webElementGuid>cb5dcfd4-4f1a-4066-ada9-748543cf1ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>509bba72-ed7d-45e4-a01f-e21e5ea39fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '1 (702) 123-4567' and @type = 'tel' and @name = 'phoneNumber']</value>
      <webElementGuid>35863e2c-817b-427d-a70b-7b1bab87f4c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
