<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reset Password_my-10 block h-14 w-ful_53d72f</name>
   <tag></tag>
   <elementGuidId>b3259bd3-7111-451b-aca3-a571382d52e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b994befd-8f6b-4a74-b276-d4e6be2a7d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36e5c638-042a-4f6a-83d2-848aafea8af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>b013fe9e-28ee-4754-8e99-02cffd06aad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>2cd5e1fb-976a-49a6-ad11-7a6b6cb9c516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d{1}</value>
      <webElementGuid>e28d6cbf-2437-4213-b31b-62d246ba5c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>0f52cc2b-65e0-48a5-8eb5-2487bd2fd0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-10 block h-14 w-full appearance-none rounded-full border border-gray-300 p-0 text-center font-bold shadow-sm placeholder:text-gray-400 focus:border-primary-400 focus:outline-none focus:ring-primary-400 sm:text-sm md:px-6 md:py-8 xl:text-base</value>
      <webElementGuid>9bb278c1-95c5-4092-ae97-25477f824d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;my-16 bg-white&quot;]/div[@class=&quot;mx-auto max-w-3xl px-4 py-10 sm:px-6 md:py-20 lg:px-8&quot;]/div[@class=&quot;shadow-default mx-auto flex max-w-2xl flex-col rounded-2xl bg-white&quot;]/div[@class=&quot;relative flex-1 px-6 py-16 md:px-20&quot;]/div[@class=&quot;grid grid-cols-6 gap-1&quot;]/input[@class=&quot;my-10 block h-14 w-full appearance-none rounded-full border border-gray-300 p-0 text-center font-bold shadow-sm placeholder:text-gray-400 focus:border-primary-400 focus:outline-none focus:ring-primary-400 sm:text-sm md:px-6 md:py-8 xl:text-base&quot;]</value>
      <webElementGuid>cec3118a-438b-47b2-a51d-623e7e1af0bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>f4de55e9-10dc-4362-b94c-c6e3fc7a4053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/div/div/div/div[3]/input</value>
      <webElementGuid>af120bdd-209b-4e36-a0b7-8b48e4ee2706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>038442c4-9fa6-4037-a05b-096dd727d02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>5538dccc-169d-43fa-ba36-249857cefed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
