<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>063cc834-01ba-4b73-8e8c-9041b4d3d330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ef97ac6-9155-46e8-9763-88629a9f6046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29b61657-ca39-4d4a-8f50-ac82ba0c89e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-r-full border border-transparent bg-primary-50 px-6 py-3 text-sm font-semibold leading-4 text-primary-400 hover:bg-primary-100 focus:ring-2 focus:ring-primary-400 focus:ring-offset-2</value>
      <webElementGuid>c0770683-0077-4714-a793-ef328b599169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>05388528-1f89-4cce-aea4-f78093bf3acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;ease-out z-50 bg-white transition-all  duration-1000&quot;]/nav[@class=&quot;fixed top-0 z-50 w-full border-b bg-white&quot;]/div[@class=&quot;mx-auto max-w-7xl px-4 sm:items-center sm:px-6 lg:px-8&quot;]/div[@class=&quot;relative flex items-center justify-between py-1.5 lg:gap-4 lg:py-2&quot;]/div[@class=&quot;w-96 hidden lg:flex lg:items-center lg:justify-end xl:col-span-4&quot;]/div[@class=&quot;inline-flex&quot;]/button[@class=&quot;rounded-r-full border border-transparent bg-primary-50 px-6 py-3 text-sm font-semibold leading-4 text-primary-400 hover:bg-primary-100 focus:ring-2 focus:ring-primary-400 focus:ring-offset-2&quot;]</value>
      <webElementGuid>ee23acc6-2c54-4ff2-99ca-393d4afd2a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>8c1c200c-0d26-47da-b9ed-a959dfeb8f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/nav/div[2]/div/div[4]/div/button[2]</value>
      <webElementGuid>72da85dc-8092-4226-b54c-81d790d685eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Sekarang'])[1]/following::button[1]</value>
      <webElementGuid>036bd2e9-3c4c-4f1c-b961-12a0dbfe5f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open sidebar'])[1]/following::button[2]</value>
      <webElementGuid>c06aa5dd-2b80-40da-a170-8d91fb8ad589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>a54f14e8-8343-455a-93ab-02e0d409e962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>b9000065-6a4d-44f9-860d-b0e700100a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>64922452-84c1-4744-a06a-3bc55b56919c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
