<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>6a1b2e24-ed65-498b-9510-4781b3a70eca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3dd0612c-250b-4323-bb14-5be2bee3bc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84720e7f-04bc-4bb5-a889-98cd65d1243a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-r-full border border-transparent bg-primary-50 px-6 py-3 text-sm font-semibold leading-4 text-primary-400 hover:bg-primary-100 focus:ring-2 focus:ring-primary-400 focus:ring-offset-2</value>
      <webElementGuid>873c4e3d-4e95-43e5-abe4-dac179ce324f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>60eb5e6f-4e22-45cd-a248-468b89274438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;ease-out z-50 bg-white transition-all  duration-1000&quot;]/nav[@class=&quot;fixed top-0 z-50 w-full border-b bg-white&quot;]/div[@class=&quot;mx-auto max-w-7xl px-4 sm:items-center sm:px-6 lg:px-8&quot;]/div[@class=&quot;relative flex items-center justify-between py-1.5 lg:gap-4 lg:py-2&quot;]/div[@class=&quot;w-96 hidden lg:flex lg:items-center lg:justify-end xl:col-span-4&quot;]/div[@class=&quot;inline-flex&quot;]/button[@class=&quot;rounded-r-full border border-transparent bg-primary-50 px-6 py-3 text-sm font-semibold leading-4 text-primary-400 hover:bg-primary-100 focus:ring-2 focus:ring-primary-400 focus:ring-offset-2&quot;]</value>
      <webElementGuid>2888b2fc-2fbe-4142-8138-a5165c044fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>b0c22a6a-1f1f-40ed-b9cc-66698374b41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/nav/div[2]/div/div[4]/div/button[2]</value>
      <webElementGuid>9a7e01f7-2698-4952-ba96-b4e6eb1b725f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Sekarang'])[1]/following::button[1]</value>
      <webElementGuid>b9644dea-29ba-4355-bb55-1f2431be6336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open sidebar'])[1]/following::button[2]</value>
      <webElementGuid>b896c769-dd10-41de-acb4-ec1b84a7887d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>2fbb1bcc-144b-4a2d-a868-3c0638d5940b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>359ee198-bfbc-447c-bafe-58af11034dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>63bad06f-d5e7-4f0a-9229-7e8535a88bf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
