<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ubisoft Entertainment_transition durati_a995e0</name>
   <tag></tag>
   <elementGuidId>99939332-3181-4ebd-8f59-6b41fbc5d23b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-panel-:r6:']/div/div/a[3]/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ed6e17d1-a66e-49c4-a98d-d0c84e5d96c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hago</value>
      <webElementGuid>dfb1731e-1e97-4aba-bc65-94cbbb3eb72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-src.vocagame.com/BisnisVocagame/hago-663b-original.webp</value>
      <webElementGuid>811ddfae-bfea-4b13-850d-195664606907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>84de38b4-241b-4dc6-9853-d1d03e420893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>2fb449fa-351a-407b-a691-f540bdda1239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition duration-300 ease-in-out</value>
      <webElementGuid>97afd993-1899-4483-ad87-e8539285f0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:r6:&quot;)/div[@class=&quot;my-4 flex flex-col&quot;]/div[@class=&quot;grid grid-cols-3 gap-3 sm:grid-cols-3 sm:gap-4 md:grid-cols-3 md:gap-2 lg:grid-cols-4 lg:gap-4 xl:grid-cols-5 xl:gap-4&quot;]/a[@class=&quot;clip-path-card relative flex h-36 w-auto flex-col overflow-hidden p-6 sm:h-52 md:h-72 md:w-56 xl:w-auto&quot;]/div[@class=&quot;clip-path-card absolute inset-0&quot;]/span[1]/img[@class=&quot;transition duration-300 ease-in-out&quot;]</value>
      <webElementGuid>2fdbd5c7-223b-4752-b808-89a0038033e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r6:']/div/div/a[3]/div/span/img</value>
      <webElementGuid>477f4840-19b4-4767-a990-03f6479b5da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hago']</value>
      <webElementGuid>2233df89-0af3-4e4e-8dbd-489bd6020736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div/span/img</value>
      <webElementGuid>b7606973-c55f-4e60-b977-fd21f992b6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Hago' and @src = 'https://static-src.vocagame.com/BisnisVocagame/hago-663b-original.webp']</value>
      <webElementGuid>26f1548b-fa47-4770-9afe-cc01b63866a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
